# Generated by Django 4.2.4 on 2023-11-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Contact",
        ),
    ]
